openapi: 3.2.0
info:
  title: Fever - Reporting Authentication API
  description: Access detailed event sales data through a reliable REST API.
  contact:
    name: Support
    email: data-support@feverup.com
  version: 1.5.0
  x-logo:
    url: https://res.cloudinary.com/fever/image/upload/ar_16:9,c_mpad,w_425/web/fever-logo-dark.jpg
servers:
- url: /v1
tags:
- name: Authentication
  description: 'This endpoint is used to authenticate a user. It requires a username and password to be passed in the request body. If

    the user is authenticated successfully, a token is returned in the response body. This token is used to authenticate the

    user in subsequent requests.


    ⚠️ The token expiration time is **30 minutes**. After that time, the user will need to authenticate again to get a new token.'
paths:
  /auth/token:
    post:
      tags:
      - Authentication
      summary: Request auth token
      description: Request JWT auth token from username and password
      operationId: create_token_auth_token_post
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Body_create_token_auth_token_post'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      x-codeSamples:
      - lang: bash
        source: "\ncurl -X POST \"https://<HOSTNAME>/v1/auth/token\" -H \"Content-Type: application/x-www-form-urlencoded\" -d 'username=<USERNAME>&password=<PASSWORD>'\n        "
        label: curl
      - lang: python
        source: "\nimport requests\n\nhostname = \"<HOSTNAME>\"\nusername = \"<USERNAME>\"\npassword = \"<PASSWORD>\"\n\nrequests.post(f\"https://{hostname}/v1/auth/token\",\n    data={\n        \"username\": username,\n        \"password\": password\n    }\n)\n        "
        label: Python
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    Body_create_token_auth_token_post:
      properties:
        username:
          type: string
          title: Username
        password:
          type: string
          format: password
          title: Password
          writeOnly: true
      type: object
      required:
      - username
      - password
      title: Body_create_token_auth_token_post
    Token:
      properties:
        access_token:
          type: string
          title: Access token
          description: The JWT access token
          example: eyJhbGc1234
        token_type:
          type: string
          title: Token type
          description: The JWT token type
          example: Bearer
      type: object
      required:
      - access_token
      - token_type
      title: Token
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
  securitySchemes:
    OAuth2PasswordBearer:
      type: oauth2
      flows:
        password:
          scopes: {}
          tokenUrl: /v1/auth/token
x-tagGroups:
- name: Endpoints
  tags:
  - Authentication
  - Billing L1
  - Billing L2
  - Carts
  - Channels
  - Customers
  - Customers Mapping
  - Deposits
  - Entitlement Configurations
  - Exchange Rates
  - FeverZone
  - Last Tour
  - Magnati
  - Neon
  - Order Items
  - Order Items Test
  - Order Sales
  - Plan Code Scans
  - Plans
  - Real Time
  - Reservations
  - SailGP
  - Sessions
  - Square
  - Webhooks
